apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: florida-man-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sjwoodr/florida-man-config
    targetRevision: main
    path: k3s-local
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
